// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.RobotA2231.commands;

import org.usfirst.frc2231.RobotA2231.AutonomousConfig;
import org.usfirst.frc2231.RobotA2231.Robot;
import org.usfirst.frc2231.utils.Direction;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class  AutoTurnRight extends Command {
	private double maxTimeout;
	private double angleToTurnRight;
    public AutoTurnRight(double angle, double timeout) {    	
    	super();
    	maxTimeout = timeout;
    	angleToTurnRight = angle;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.driveTrain.initializeEncoders();
    	setTimeout(maxTimeout);
    }


	@Override
	protected void execute() {
		// TODO Auto-generated method stub
		Robot.driveTrain.turn(Direction.RIGHT);
	}
	

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return Math.abs(Robot.driveTrain.posRight()) >= 59.5 * (angleToTurnRight / 360) * Math.PI - 2.5 || isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.stop();
    }

	@Override
	protected void interrupted() {
		// TODO Auto-generated method stub
		
	}
}
