// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2231.commands;
import org.usfirst.frc2231.Robot2231.AutonomousConfig;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoAllBoxes extends CommandGroup {
    
    public  AutoAllBoxes() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.
    	addSequential(new ResetElevator());
    	addParallel(new LiftToLevel1());
    	addParallel(new RemoveWithWheels());
    	addSequential(new AutoTurnRight(26, 0.5)); //for overhauled auto
       	addSequential(new AutoDriveForward(75, 1.5)); //remove for overhauled auto
    	addSequential(new AutoTurnLeft(112, 1.2));
    	addParallel(new StopCollectorWheels());
    	addSequential(new AutoDriveForward(63, 0.9));
    	//addSequential(new InsertCrate());
    	addSequential(new CloseWheels());
    	//addSequential(new ResetElevator());
    	//addParallel(new LiftToLevel1());
    	//addParallel(new RemoveWithWheels());
    	addParallel(new InsertCrate());
    	addSequential(new AutoTurnLeft(10, 1.8));   
    	addSequential(new ResetElevator());
    	addParallel(new LiftToLevel1());
    	addSequential(new AutoDriveForward(40, 1.5)); //remove for overhauled auto
    	addSequential(new AutoTurnRight(50	, 1.1));
    	addSequential(new AutoDriveForward(63, 0.9));    	
    	addSequential(new InsertCrate());
    	addSequential(new ResetElevator());
    	addParallel(new AutoTurnRight(90, 2.2*AutonomousConfig.TURN_RIGHT_TIME));
    	addSequential(new AutoDriveForward(200, 2));
    	addSequential(new AutoDriveForward(200, 2));
    	
        // To run multiple 	commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
