// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2231.commands;

import org.usfirst.frc2231.Robot2231.Robot;
import org.usfirst.frc2231.Robot2231.subsystems.Stackevator;

/**
* A general command which moves the elevator to a specific point
* Inheriting classes must set the variable setPoint to the desired value.
*/
public class  GeneralSetpointCommand extends GeneralStackevatorCommand {

	protected double setPoint;
	
    public GeneralSetpointCommand() {
        super();
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	// If going down add offset to the setpoint
    	Robot.stackevator.setGoingDown(Robot.stackevator.getPosition() > setPoint);
    	if (Robot.stackevator.isGoingDown()){
    		Robot.stackevator.setSetpoint(setPoint + Stackevator.GOING_DOWN_OFFSET);
    	}
    	else {
    		Robot.stackevator.setSetpoint(setPoint);
    	}
    	Robot.stackevator.enable();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return Robot.stackevator.onTarget();
    }
        
}
