// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2231.commands;

import org.usfirst.frc2231.Robot2231.AutonomousConfig;
import org.usfirst.frc2231.Robot2231.subsystems.Stackevator;

/**
 * Moves the elevator to level 1(can put crates on 1 crates)
 */
public class  LiftToLevel1 extends GeneralSetpointCommand {

    public LiftToLevel1() {
    	super();
    	setPoint = Stackevator.LEVEL_1_POSITION;
    	maxTimeout = AutonomousConfig.TIME_LIFT_LEVEL_1;
    }
}
