// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2231.commands;

import org.usfirst.frc2231.Robot2231.Robot;

/**
 * Moves the elevator to the bottom and resets encoder
 */
public class  ResetElevator extends GeneralStackevatorCommand{

	boolean resetWithPID;
	
    public ResetElevator() {
        super();
        resetWithPID = false;
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
    	if (Robot.stackevator.getCalibrated()) {
    		Robot.stackevator.setSetpoint(0);
    		Robot.stackevator.enable();
    		resetWithPID = true;
    	}
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (resetWithPID && Robot.stackevator.onTarget() && !Robot.stackevator.reachedBottom()) {
    		resetWithPID = false;
    	}
    	if (!resetWithPID) {
    		Robot.stackevator.lower();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.stackevator.reachedBottom();
    }

    // Called once after isFinished returns true
    protected void end() {
    	super.end();
    	Robot.stackevator.resetEncoder();
    	Robot.stackevator.setCalibrated(true);
    }

}
