// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.RobotA2231.subsystems;

import org.usfirst.frc2231.RobotA2231.RobotMap;
import org.usfirst.frc2231.RobotA2231.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Arms extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Compressor comp = RobotMap.armscomp;
    Solenoid openArms = RobotMap.armsopenArms;
    Solenoid closeArms = RobotMap.armscloseArms;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    boolean opened = false;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void changeCompStat(boolean start)
    {
    	if(start)
    		comp.start();
    	else
    		comp.stop();
    }
    
    public void changeArmsState(boolean toOpen)
    {
    	if(toOpen)
    	{
    		openArms.set(true);
    		closeArms.set(false);
    		opened = true;
    	}
    	else
    	{
    		openArms.set(false);
    		closeArms.set(true);
    		opened = false;
    	}
    }
    
    public boolean isOpened()
    {
    	return opened;
    }
    
    public void checkOpened()
    {
    	if (openArms.get())
    		opened = true;
    	else
    		opened = false;
    }
}

