// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* functionStick;
	JoystickButton* stopComp;
	JoystickButton* startComp;
	JoystickButton* close;
	JoystickButton* open;
	JoystickButton* level1;
	JoystickButton* liftWithJoystickButton;
	JoystickButton* level2;
	JoystickButton* resetButton;
	Joystick* driveStick;
	JoystickButton* openWheelsButton;
	JoystickButton* closeWheelsButton;
	JoystickButton* stopWheelsButton;
	JoystickButton* insertCrateButton;
	JoystickButton* rotateRightButton;
	JoystickButton* rotateLeftButton;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getdriveStick();
	Joystick* getfunctionStick();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
