// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.Robot2014;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontLeftMotor;
    public static SpeedController driveTrainFrontRightMotor;
    public static SpeedController driveTrainrearLeftMotor;
    public static SpeedController driveTrainrearRightMotor;
    public static RobotDrive driveTrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeftMotor = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "FrontLeftMotor", (Talon) driveTrainFrontLeftMotor);
        
        driveTrainFrontRightMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "FrontRightMotor", (Talon) driveTrainFrontRightMotor);
        
        driveTrainrearLeftMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "rearLeftMotor", (Talon) driveTrainrearLeftMotor);
        
        driveTrainrearRightMotor = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "rearRightMotor", (Talon) driveTrainrearRightMotor);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainFrontLeftMotor, driveTrainFrontRightMotor,
              driveTrainrearLeftMotor, driveTrainrearRightMotor);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
