// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2231.testingPIDelevator;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput stackevatorbottom;
    public static Encoder stackevatorencoder;
    public static SpeedController stackevatormotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        stackevatorbottom = new DigitalInput(6);
        LiveWindow.addSensor("Stackevator", "bottom", stackevatorbottom);
        
        stackevatorencoder = new Encoder(7, 8, false, EncodingType.k4X);
        LiveWindow.addSensor("Stackevator", "encoder", stackevatorencoder);
        stackevatorencoder.setDistancePerPulse(1.0);
        stackevatorencoder.setPIDSourceParameter(PIDSourceParameter.kDistance);
        stackevatormotor = new Victor(4);
        LiveWindow.addActuator("Stackevator", "motor", (Victor) stackevatormotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
